### ISSUE TITLE
Validation not working on findOneAndUpdate even when {context:'query'} is set

### ISSUE THREAD

**Issue by Srivatsav-K** [mongoose-unique-validator/mongoose-unique-validator#138]
// controller
enquiryControllers.update = (req, res) => {
    const userId = req.user._id
    const id = req.params.id
    const body = req.body

    Enquiry.findOneAndUpdate({ _id: id, user: userId }, body, { new: true, runValidators: true, context: 'query' })
        .populate({
            path: 'contact', select: ['name', 'email', 'phone'],
            populate: { path: 'client', select: 'name' }
        }).populate('user', 'username')
        .then((enquiry) => {
            if (!enquiry) {
                res.json({ errors: 'Not found!' })
            } else {
                res.json(enquiry)
            }
        })
        .catch((err) => {
            res.json(err)
        })
}

//model

const enquirySchema = new Schema({
    name: {
        type: String,
        required: [true, '{PATH} is required!'],
        minLength: [3, '{PATH} must have at least 3 characters '],
        unique: true,
        trim: true,
        lowercase: true
    },
    contact: {
        type: Schema.Types.ObjectId,
        ref: 'Contact',
        required: [true, '{PATH} name is required!']
    },
    requirements: {
        type: String,
        required: [true, '{PATH} are requied!'],
        trim: true
    },
    budget: {
        type: Number,
        required: [true, '{PATH} is required!'],
        min: [1, '{PATH} should be greater or equal to 1'],
        trim: true
    },
    competitors: {
        type: String,
        trim: true
    },
    estimatedTimelines: {
        type: String
    },
    expectedClosingDate: {
        type: Date
    },
    status: {
        type: String,
        default: 'inprocess',
        enum: ['inprocess', 'orderplaced', 'not interested']
    },
    comments: {
        type: [commentsSchema],
    },
    user: {
        type: Schema.Types.ObjectId,
        ref: 'User'
    }
})

enquirySchema.plugin(uniqueValidator, { message: '{PATH} exists!' })

const Enquiry = mongoose.model('Enquiry', enquirySchema)

module.exports = Enquiry

**Comment by gatorhatur** [comment]
Consider using FindOneAndReplace instead. According to the mongoose documentation, validation only triggers on the fields that were actually updated. Overwriting the existing copy seems to work the best for me.
