### ISSUE TITLE
mongoose-unique-validator doesn't work with Mongoose 7

### ISSUE THREAD

**Issue by Achilles0509** [mongoose-unique-validator/mongoose-unique-validator#142]
https://mongoosejs.com/docs/migrating_to_7.html#dropped-callback-support

In Mongoose7 callback support dropped for `countDocuments` function.
But `mongoose-unique-validator` rely `countDocuments` function's callback, so it throws error.

`Query.prototype.countDocuments() no longer accepts a callback`

**Comment by maybesmurf** [comment]
is this gonna be merged or what

**Comment by viveleroi** [comment]
Fixed via ce3e35a53f4400c2188519f4777ceb1af7ba05fe
