### ISSUE TITLE
Waiting for a version to be released for mongoose 8

### ISSUE THREAD

**Issue by 834N5** [mongoose-unique-validator/mongoose-unique-validator#152]
Will a new version be released to work with mongoose 8?
I see that the tests have been fixed here 2a737c5768a3d5b13d1a46beea3d1f8442567051

Currently both the [npm package](https://www.npmjs.com/package/mongoose-unique-validator) and releases are still at 4.0.0
I'd like to be able to install the package from npm without having to --force it.

**Comment by viveleroi** [comment]
Published as v5
