### ISSUE TITLE
this.parent is not a function

### ISSUE THREAD

**Issue by varunhhhrahul** [mongoose-unique-validator/mongoose-unique-validator#153]
Hi guys, getting an error in mongoose 7.8.4 with version 4.0.0 that `_id: ValidatorError: this.parent is not a function`, tried to upgrade it to package to 5.0.0 still the same error, seems like `this.parent()` definition is missing, if I replace `this.parent()` with `this.ownerDocument()` then create and save works fine.

Line:
`index.js:81:56`

**Comment by viveleroi** [comment]
Please provide a failing test or a reproduction repository, otherwise there's not enough context to debug and fix this.

**Comment by varunhhhrahul** [comment]
![Screenshot 2024-02-21 at 1 06 26 AM](https://github.com/mongoose-unique-validator/mongoose-unique-validator/assets/44650484/aef1a06d-6d4c-44a0-a78d-cf6e7b1e5492)

These are the errors that I am getting

**Comment by viveleroi** [comment]
Posting the error doesn't help. Without a reproduction I can't tell what led to the issue.
